<?php 
/**
 * Implements hook_commerce_payment_method_info().
 */
function erip_expresspay_commerce_payment_method_info() {
  return array(
    // Системное название способа оплаты.
    'erip_expresspay' => array(
      // Название способа оплаты для отображения в админке.
      'title' => t('Экспресс Платежи: ЕРИП'),
      // Название способа оплаты для отображения в форме чекаута. Может содержать html.
      // Опционально.
      'display_title' => t('ЕРИП'),
      // Описание способа оплаты. Опционально.
      'description' => t('Выставление счетов в ЕРИП для оплаты.'),
      // Состояние способа оплаты при включении модуля: TRUE — включён, FALSE — выключен
      // (по умолчанию). Опционально.
      'active' => TRUE,
      // Сможет ли администратор самостоятельно добавить этот способ оплаты для
      // завершённого заказа. Опционально. По умолчанию TRUE.
      'terminal' => TRUE,
      // Нужно ли покупателю покидать пределы сайта при оплате заказа этим способом.
      // Опционально. По умолчанию FALSE.
      'offsite' => FALSE,
      // Автоматический редирект на сторонний сайт при оплате заказа этим способом.
      // Опционально. По умолчанию FALSE.
      'offsite_autoredirect' => FALSE,
    ),
  );
}

/**
 * Payment method callback: settings form.
 */
function erip_expresspay_settings_form($settings = NULL) {
  $form = array();
  $settings = (array)$settings + array(
    'token' => '',
    'handler_url' => $GLOBALS['base_root'] . '/?wc-api=wc_erip_expresspay&action=notify',
    'sign_invoices' => false,
    'secret_key' => '',
    'sign_notify' => false,
    'secret_key_norify' => '',
    'name_editable' => false,
    'address_editable' => false,
    'amount_editable' => false,
    'test_mode' => false,
    'url_api' => 'https://api.express-pay.by',
    'url_sandbox_api' => 'https://sandbox-api.express-pay.by',
    'message_success' => 'Для оплаты заказа Вам необходимо перейти в раздел ЕРИП:

Интернет-магазины\Сервисы -> "Первая буква доменного имени интернет-магазина" -> "Доменное имя интернет-магазина"

Далее введите номер заказа "##order_id##" и нажмите "продолжить".

После поступления оплаты Ваш заказ поступит в обработку.', 'wc_erip_expresspay',
  );
 
  // Пример настройки — идентификатор магазина
  $form['token'] = array(
    '#type' => 'textfield',
    '#title' => t('Токен'),
    '#description' => t('Генерирутся в панели express-pay.by'),
    '#default_value' => $settings['token'],
  );
  $form['handler_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Адрес для уведомлений'),
    '#default_value' => $settings['handler_url'],
    '#disabled' => true,
  );
  $form['sign_invoices'] = array(
    '#type' => 'checkbox',
    '#title' => t('Использовать цифровую подпись для API'),
    '#description' => t('Параметр проверки запросов с использование цифровой подписи'),
    '#default_value' => $settings['sign_invoices'],
  );
  $form['secret_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Секретное слово для подписи счетов'),
    '#description' => t('Секретного слово, которое известно только серверу и клиенту. Используется для формирования цифровой подписи. Задается в панели express-pay.by'),
    '#default_value' => $settings['secret_key'],
  );
  $form['sign_notify'] = array(
    '#type' => 'checkbox',
    '#title' => t('Использовать цифровую подпись для уведомлений'),
    '#description' => t('Параметр проверки запросов с использование цифровой подписи'),
    '#default_value' => $settings['sign_notify'],
  );
  $form['secret_key_norify'] = array(
    '#type' => 'textfield',
    '#title' => t('Секретное слово для подписи уведомлений'),
    '#description' => t('Секретного слово, которое известно только серверу и клиенту. Используется для формирования цифровой подписи. Задается в панели express-pay.by'),
    '#default_value' => $settings['secret_key_norify'],
  );
  $form['name_editable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Разрешено изменять ФИО плательщика'),
    '#description' => t('Разрешается при оплате счета изменять ФИО плательщика'),
    '#default_value' => $settings['name_editable'],
  );
  $form['address_editable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Разрешено изменять адрес плательщика'),
    '#description' => t('Разрешается при оплате счета изменять адрес плательщика'),
    '#default_value' => $settings['address_editable'],
  );
  $form['amount_editable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Разрешено изменять сумму оплаты'),
    '#description' => t('Разрешается при оплате счета изменять сумму платежа'),
    '#default_value' => $settings['amount_editable'],
  );
  $form['test_mode'] = array(
    '#type' => 'checkbox',
    '#title' => t('Использовать тестовый режим'),
    '#default_value' => $settings['test_mode'],
  );
  $form['url_api'] = array(
    '#type' => 'textfield',
    '#title' => t('Адрес API'),
    '#default_value' => $settings['url_api'],
  );
  $form['url_sandbox_api'] = array(
    '#type' => 'textfield',
    '#title' => t('Адрес тестового API'),
    '#default_value' => $settings['url_sandbox_api'],
  );
  $form['message_success'] = array(
    '#type' => 'textarea',
    '#title' => t('Сообщение при успешном заказе'),
    '#default_value' => $settings['message_success'],
  );
 
  return $form;
}
?>